name: Branch Commit Buildkite Plugin
description: Checks that a commit is present on the branch defined by the BUILDKITE_BRANCH variable. Best suited for UI builds.
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    mode:
      type: string
      description: "Validation mode. In strict mode, a branch mismatch fails the build. In warn mode, it logs a warning."
      enum:
        - warn
        - strict
      default: "strict"
  additionalProperties: false
