name: Commit Branch Buildkite Plugin
description: Checks that a commit it present on the branch defined by the BUILDKITE_BRANCH variable. Best suited for UI builds.
author: https://github.com/buildkite-plugins
requirements:
  - bash
configuration:
  properties:
    mode:
      type: string
  required:
    - mandatory
  additionalProperties: false
